// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyEFDataLibrary.Models;

public partial class BusinessUnit : MyEntity
{
    [Key]
    [Column("BusinessUnitID")]
    public int BusinessUnitId { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Summary { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    public string Url { get; set; }

    [Required]
    public string ImageFilename { get; set; }


    [InverseProperty("BusinessUnit")]
    public virtual ICollection<ReportRole> ReportRoles { get; set; } = new List<ReportRole>();
}