// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyEFDataLibrary.Models;

public partial class Report : MyEntity
{
    [Key]
    [Column("ReportID")]
    public int ReportId { get; set; }

    [Required]
    public string Name { get; set; }

    public string Description { get; set; }

    [Column("PBI_ReportID")]
    public Guid? PbiReportId { get; set; }

    public string Summary { get; set; }

    public string Metadata { get; set; }


    [InverseProperty("Report")]
    public virtual ICollection<ReportRole> ReportRoles { get; set; } = new List<ReportRole>();
}