// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyEFDataLibrary.Models;

public partial class UserType : MyEntity
{
    [Key]
    [Column("UserTypeID")]
    public int UserTypeId { get; set; }

    [Required]
    public string Name { get; set; }


    [InverseProperty("UserType")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}