// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyEFDataLibrary.Models;

[Index("ObjectId", Name = "AzureObjIDUnique", IsUnique = true)]
[Index("UserTypeId", Name = "IX_Users_UserTypeID")]
public partial class User : MyEntity
{
    [Key]
    [Column("UserID")]
    public int UserId { get; set; }

    [Required]
    [StringLength(450)]
    public string UserLogon { get; set; }

    public string FullName { get; set; }

    [Column("UserTypeID")]
    public int UserTypeId { get; set; }


    [Column("ObjectID")]
    [StringLength(100)]
    public string ObjectId { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    [ForeignKey("UserTypeId")]
    [InverseProperty("Users")]
    public virtual UserType UserType { get; set; }
}